### ISSUE TITLE
DllNotFoundException: ViSPUnity

### ISSUE THREAD

**Issue by rjth** [lagadic/visp_unity#14]
I am running into a DllNotFoundException: ViSPUnity error when running the scene on `Script_mbt.Update () (at Assets/Scripts/Script_mbt.cs:103)`.

Reimporting, moving the DLL did not fix the issue. I am running the project on 2017.4.3f1

**Comment by redgene** [comment]
Hi @rjth, you need to generate dll on your architecture using the instructions provided [here](https://github.com/lagadic/visp_unity/wiki/Generating-DLL) and then import that into Unity Assets folder.

**Comment by SynFbecker** [comment]
Hi @redgene, I'm running into the same error (DllNotFoundException: ViSPUnity) when I run scene_ar in the Editor. Here is the full error:
`DllNotFoundException: ViSPUnity
Script_ar.Update () (at Assets/Scripts/Script_ar.cs:71)`

The dll I use is the one I generated following the instructions from the Wiki. I'm using Unity 2017.4.4f1

**Comment by WVbrU** [comment]
@redgene, I am getting the same error as the others. When running scene_ar in the editor, I get the error:

> DllNotFoundException: ViSPUnity Script_ar.Update () (at Assets/Scripts/Script_ar.cs:67)

Line 67 is:
`AprilTagFunctionsCombined(Color32ArrayToByteArray(wct.GetPixels32()), wct.height, wct.width, cam_px, cam_py, cam_u0, cam_v0, coord, U, V, T, h, w, apr);`

I generated the .dll using your instructions and pasted it into the Assets folder with Unity 2017.4.2f2. Thanks!

**Comment by WVbrU** [comment]
Update: I found out that in my case, that Unity could not find the .dll's ViSPUnity.dll was dependent on. To fix it, I added the folder in ViSPUnity_master with those .dll's to the Path environment variable.

**Comment by RobGiffin** [comment]
> Update: I found out that in my case, that Unity could not find the .dll's ViSPUnity.dll was dependent on. To fix it, I added the folder in ViSPUnity_master with those .dll's to the Path environment variable.

Hi @WVbrU I'm struggling with exactly the same issue, I've built the DLL as required following the guide (64bit architecture using VS 2017).  And get exactly the same error.  Could you explain exactly what path/dll's ViSPUnity.dll is dependant on as I can't spot this myself.  Thanks

**Comment by RobGiffin** [comment]
> Hi @WVbrU I'm struggling with exactly the same issue, I've built the DLL as required following the guide (64bit architecture using VS 2017). And get exactly the same error. Could you explain exactly what path/dll's ViSPUnity.dll is dependant on as I can't spot this myself. Thanks

Don't worry I found the solution.  It was obvious what I was missing when I tested the 'ViSP data set' using the guide below.  When I ran the displayGDI.exe it showed which dll's couldn't be found due to missing path statements.  

https://visp-doc.inria.fr/doxygen/visp-daily/tutorial-install-win10-msvc15.html#install_win10_msvc15_dataset

It showed that I was missing the path for opencv and the dll's I'd built.  So I added the following two lines to the path statement.  Having done this the Unity ViSPUnity.dll is now working correctly.

C:\opencv\build\x64\vc15\bin
C:\visp-ws\visp-build-vc15\x64\vc15\bin\Release

**Comment by Mayikami** [comment]
I am getting the same error as the others.I tried everything.

**Comment by drewsherlock** [comment]
I used Process Monitor (https://www.codeproject.com/Articles/560816/Troubleshooting-dependency-resolution-problems-usi) to find the dll I was missing / didn't have in my path.

For me it was libzbar64-0.dll which I'd built but not added its location to the path.

**Comment by houssem1994** [comment]
Hi guys i am still struggling with this error , can someone help me please !! 
i did all the steps that you monshined before and i still have the same error  
i built the .dll 
i added the path statement 
however the dll that i am missing are a lot 
** please help **

**Comment by fspindle** [comment]
Try first to run an example coming with ViSP like the one in `C:\visp-ws\visp-build-vc15\example\device\display\Release\displayGDI.exe` and add all the missing libraries to your path var

**Comment by USER1999-svg** [comment]
i still have the same problem ..
I am running into a DllNotFoundException: ViSPUnity error when running the scene on Script_mbt.Update () (at Assets/Scripts/Script_mbt.cs:103).

**Comment by fspindle** [comment]
The first thing to do is to ensure that you are using the right `ViSPUnity.dll` file. To this end:
- close Unity
- with  Windows Explorer navigate to `C:/.../visp_unity/unityProject/Assets` and delete `ViSPUnity.dll` and `ViSPUnity.dll.meta` files
- copy  `C:/.../visp_unity/vispWrapper/build/Release/ViSPUnity.dll` into `C:/.../visp_unity/unityProject/Assets`
- start unity and open the project again. The issue should be fixed

If this is not the case, check the following:
- ViSP and vispWrapper Visual Studio projects should be configured in CMakeGUI with the same platform generator option (I recommend to use `x64`). This is done following ViSP installation quick start [tutorial](https://visp-doc.inria.fr/doxygen/visp-daily/tutorial-install-win10-msvc15.html#install_win10_msvc15_quick). Same could be done for vispWrapper project adding `-DVISP_DIR=C:/visp-ws/visp-build-vc15/install` option to the `cmake` command line
- ViSP and ViSPWrapper should be build in Release configuration
- Check that all the DLLs (the one for ViSP and for all the 3rd parties like OpenCV...) locations are added in `PATH` environment variable (see [tutorial](https://visp-doc.inria.fr/doxygen/visp-daily/tutorial-install-win10-msvc15.html#install_win10_msvc15_env_var))
- Note that there is no need to add the location of `ViSPUnity.dll` in the `PATH` environment variable
- Test the previous point opening a `cmd` command line window, entering in `C:/visp-ws/visp-build-vc15/tutorial/image/Release` folder and running `tutorial-image-viewer.exe`

**Comment by tarek933** [comment]
thank's a lot .
I solve it by adding .dll needed like Coin4.dll missed .
@fspindle Itry now to use this exemple to do a tracking of object without apriltag using generic tutorial ; my code. cpp is tutorial-mb-generic-tracker-live.cpp with Wrl model .. Im bigger with C# ,, is there any tutorial or C#source code can help me to use this exemple with unity ?
