### ISSUE TITLE
'computeCurrentProjectionError' : is not a member of 'vpMbGenericTracker'

### ISSUE THREAD

**Issue by SynFbecker** [lagadic/visp_unity#15]
I'm trying to generate ViSPUnity.dll in Visual Studio 2017 using the instructions provided by the Wiki.
I followed the instructions step by step to install ViSP 3.1.0 for Windows with Visual C++ 2017 (vc15), everything worked fine. But when I apply Build on ViSPUnity solution, I get this error:
`C2039	'computeCurrentProjectionError' : is not a member of 'vpMbGenericTracker'	ViSPUnity	c:\workplace\vispwrapper\vispunity.cpp	195`

**Comment by redgene** [comment]
hi @SynFbecker, thanks for pointing this out. vpMbGenericTracker was introduced after 3.1.0. Please download the next coming release 3.2.0 snapshot from [here](https://visp.inria.fr/download/) or [GitHub](https://github.com/lagadic/visp) for latest visp. Sorry for inconvenience, I will update the wiki.

**Comment by redgene** [comment]
hi @SynFbecker, thanks for pointing this out. Please download the next coming release 3.2.0 snapshot from [here](https://visp.inria.fr/download/) or [GitHub repo](https://github.com/lagadic/visp) for latest visp. Sorry for inconvenience, I will update the wiki.

**Comment by SynFbecker** [comment]
Hi @redgene, thanks for your answer. I was able to generate the dll just fine.
