### ISSUE TITLE
Wrong results

### ISSUE THREAD

**Issue by Syntax134** [lagadic/visp_unity#16]
Hi, I always get the following result, when starting the project from within Unity, although I calibrated my camera of course. Does anyone know what issue this could be?
I am using ViSP 3.2.0 together with Unity 2018.2.14f1.

![capture](https://user-images.githubusercontent.com/8775492/51998081-4616ea00-24b8-11e9-9e52-148cb4e70354.JPG)

**Comment by fspindle** [comment]
To debug you should start with an initial position where 3 faces are visible. In the image you attached to your post, you have only 2 faces and I'm not completly sure that the upper face is considered as visible by the tracker. It depends on the [visibility settings](https://visp-doc.inria.fr/doxygen/visp-daily/tutorial-tracking-mb-generic.html#mb_generic_settings_visibility) you are using. If only one face is visible (here the front face) it could explain the drift.

An other possible reason could be the following. The pose returned by `vpAprilTag` and `vpMbGenricTracker` is right handed. Unity uses left handed coordinates. There could be something wrong in the projection and especially the way the rotation is taken into account. To debug try to display over the image the cMo frame attached to the tag and the one attached to the cube.

**Comment by fspindle** [comment]
This post is too late now but if other users have the same behavior I would suggest to check if you updated the camera parameters corresponding to your camera (after [calibration](https://visp-doc.inria.fr/doxygen/visp-daily/tutorial-calibration-intrinsic.html)) in the plane Game Object (see [image](https://raw.githubusercontent.com/redgene/visp_unity/master/wiki/Unity/InspectorWindow_scene_mbt.PNG)). `Cam_u 0` and `Cam_v 0` should roughly correspond to the half image width and height respectively, while `Cam_py` and `Cam_py` could only be obtained by [calibration](https://visp-doc.inria.fr/doxygen/visp-daily/tutorial-calibration-intrinsic.html).

**Comment by fspindle** [comment]
This issue occurs when your tag size and cube size differ from the values in the code.
There is now the ability to tune these parameters, see PR #21.
