### ISSUE TITLE
cao 3d model tracking in unity using visp  

### ISSUE THREAD

**Issue by houssem1994** [lagadic/visp_unity#17]
we already tested the .dll of the apriltag example  and we want to use visp cao 3d model tracking in unity, can you please guide us through , what functions we need and how to create and generate the adequate  .dll so we can use in unity

**Comment by fspindle** [comment]
From your post in #14, it sounds that you didn't succeed to run the Unity [tutorials ](https://visp-doc.inria.fr/doxygen/visp-daily/index.html#tuto_unity)

There is already a starting [example ](https://github.com/lagadic/visp_unity/wiki/Running-in-Unity) for 3d model tracking using a cao file. Running and understanding this example should help you to do the same with an other object.

**Comment by akashcastelino** [comment]
Does the model based tracker only accept CAO files or other 3d cad formats as well?

**Comment by fspindle** [comment]
The main supported format is .cao. There is also .vrml format that is supported, but with less capabilities. It needs Coin 3rd-party to be able to parse the vrml file.

**Comment by sara87777** [comment]
c'est quoi la taille maximale des fichiers vrml supportés?
