### ISSUE TITLE
Building wrapper fail

### ISSUE THREAD

**Issue by LungTakumi** [lagadic/visp_unity#22]
Building unity wrapper failed. Followed the tutorial here: https://github.com/lagadic/visp_unity/wiki/Generating-ViSP-wrapper-plugin

After excuting these commands:

cd visp_unity

mkdir vispWrapper-build

cd vispWrapper-build

cmake -G "Visual Studio 16 2019" -A "x64" %VISP_WS%\vispWrapper -DVISP_DIR=%VISP_WS%\visp-build-vc16\install

cmake --build . --config Release

Then, below are the error messages:

Microsoft (R) Build Engine version 16.5.0+d4cbfca49 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  Checking Build System
  Building Custom Rule D:/VisualStudioPJ/visp-ws/visp_unity/vispWrapper/CMakeLists.txt
  ViSPUnity.cpp
D:\VisualStudioPJ\visp-ws\visp-build-vc16\install\include\visp3/core/vpConfig.h(1,1): warning C4819: The file contains
a character that cannot be represented in the current code page (936). Save the file in Unicode format to prevent data
loss [D:\VisualStudioPJ\visp-ws\visp_unity\vispWrapper-build\ViSPUnity.vcxproj]
D:\VisualStudioPJ\visp-ws\visp-build-vc16\install\include\visp3/mbt/vpMbGenericTracker.h(483,1): warning C4819: The fil
e contains a character that cannot be represented in the current code page (936). Save the file in Unicode format to pr
event data loss [D:\VisualStudioPJ\visp-ws\visp_unity\vispWrapper-build\ViSPUnity.vcxproj]
D:\VisualStudioPJ\visp-ws\visp_unity\vispWrapper\ViSPUnity.cpp(85,1): warning C4273: 'Visp_EnableDisplayForDebug': inco
nsistent dll linkage [D:\VisualStudioPJ\visp-ws\visp_unity\vispWrapper-build\ViSPUnity.vcxproj]
D:\VisualStudioPJ\visp-ws\visp_unity\vispWrapper\ViSPUnity.h(71,6): message : see previous definition of 'Visp_EnableDi
splayForDebug' [D:\VisualStudioPJ\visp-ws\visp_unity\vispWrapper-build\ViSPUnity.vcxproj]
D:\VisualStudioPJ\visp-ws\visp_unity\vispWrapper\ViSPUnity.cpp(90,1): warning C4273: 'Visp_WrapperFreeMemory': inconsis
tent dll linkage [D:\VisualStudioPJ\visp-ws\visp_unity\vispWrapper-build\ViSPUnity.vcxproj]
D:\VisualStudioPJ\visp-ws\visp_unity\vispWrapper\ViSPUnity.h(77,6): message : see previous definition of 'Visp_WrapperF
reeMemory' [D:\VisualStudioPJ\visp-ws\visp_unity\vispWrapper-build\ViSPUnity.vcxproj]
D:\VisualStudioPJ\visp-ws\visp_unity\vispWrapper\ViSPUnity.cpp(110,1): warning C4273: 'Visp_ImageUchar_SetFromColor32Ar
ray': inconsistent dll linkage [D:\VisualStudioPJ\visp-ws\visp_unity\vispWrapper-build\ViSPUnity.vcxproj]
D:\VisualStudioPJ\visp-ws\visp_unity\vispWrapper\ViSPUnity.h(86,6): message : see previous definition of 'Visp_ImageUch
ar_SetFromColor32Array' [D:\VisualStudioPJ\visp-ws\visp_unity\vispWrapper-build\ViSPUnity.vcxproj]
D:\VisualStudioPJ\visp-ws\visp_unity\vispWrapper\ViSPUnity.cpp(130,1): warning C4273: 'Visp_MbGenericTracker_SetFeature
Type': inconsistent dll linkage [D:\VisualStudioPJ\visp-ws\visp_unity\vispWrapper-build\ViSPUnity.vcxproj]
D:\VisualStudioPJ\visp-ws\visp_unity\vispWrapper\ViSPUnity.h(101,6): message : see previous definition of 'Visp_MbGener
icTracker_SetFeatureType' [D:\VisualStudioPJ\visp-ws\visp_unity\vispWrapper-build\ViSPUnity.vcxproj]
D:\VisualStudioPJ\visp-ws\visp_unity\vispWrapper\ViSPUnity.cpp(140,1): warning C4273: 'Visp_MbGenericTracker_SetMovingE
dgesSettings': inconsistent dll linkage [D:\VisualStudioPJ\visp-ws\visp_unity\vispWrapper-build\ViSPUnity.vcxproj]
D:\VisualStudioPJ\visp-ws\visp_unity\vispWrapper\ViSPUnity.h(111,6): message : see previous definition of 'Visp_MbGener
icTracker_SetMovingEdgesSettings' [D:\VisualStudioPJ\visp-ws\visp_unity\vispWrapper-build\ViSPUnity.vcxproj]
D:\VisualStudioPJ\visp-ws\visp_unity\vispWrapper\ViSPUnity.cpp(153,1): warning C4273: 'Visp_MbGenericTracker_SetKeypoin
tSettings': inconsistent dll linkage [D:\VisualStudioPJ\visp-ws\visp_unity\vispWrapper-build\ViSPUnity.vcxproj]
D:\VisualStudioPJ\visp-ws\visp_unity\vispWrapper\ViSPUnity.h(119,6): message : see previous definition of 'Visp_MbGener
icTracker_SetKeypointSettings' [D:\VisualStudioPJ\visp-ws\visp_unity\vispWrapper-build\ViSPUnity.vcxproj]
D:\VisualStudioPJ\visp-ws\visp_unity\vispWrapper\ViSPUnity.cpp(154,56): error C2039: 'KLT_TRACKER': is not a member of
'vpMbGenericTracker' [D:\VisualStudioPJ\visp-ws\visp_unity\vispWrapper-build\ViSPUnity.vcxproj]
D:\VisualStudioPJ\visp-ws\visp-build-vc16\install\include\visp3/mbt/vpMbGenericTracker.h(80): message : see declaration
 of 'vpMbGenericTracker' [D:\VisualStudioPJ\visp-ws\visp_unity\vispWrapper-build\ViSPUnity.vcxproj]
D:\VisualStudioPJ\visp-ws\visp_unity\vispWrapper\ViSPUnity.cpp(154,67): error C2065: 'KLT_TRACKER': undeclared identifi
er [D:\VisualStudioPJ\visp-ws\visp_unity\vispWrapper-build\ViSPUnity.vcxproj]
D:\VisualStudioPJ\visp-ws\visp_unity\vispWrapper\ViSPUnity.cpp(155,5): error C2065: 'vpKltOpencv': undeclared identifie
r [D:\VisualStudioPJ\visp-ws\visp_unity\vispWrapper-build\ViSPUnity.vcxproj]
D:\VisualStudioPJ\visp-ws\visp_unity\vispWrapper\ViSPUnity.cpp(155,17): error C2146: syntax error: missing ';' before i
dentifier 'klt_settings' [D:\VisualStudioPJ\visp-ws\visp_unity\vispWrapper-build\ViSPUnity.vcxproj]
D:\VisualStudioPJ\visp-ws\visp_unity\vispWrapper\ViSPUnity.cpp(155,17): error C2065: 'klt_settings': undeclared identif
ier [D:\VisualStudioPJ\visp-ws\visp_unity\vispWrapper-build\ViSPUnity.vcxproj]
D:\VisualStudioPJ\visp-ws\visp_unity\vispWrapper\ViSPUnity.cpp(156,5): error C2065: 'klt_settings': undeclared identifi
er [D:\VisualStudioPJ\visp-ws\visp_unity\vispWrapper-build\ViSPUnity.vcxproj]
D:\VisualStudioPJ\visp-ws\visp_unity\vispWrapper\ViSPUnity.cpp(157,5): error C2065: 'klt_settings': undeclared identifi
er [D:\VisualStudioPJ\visp-ws\visp_unity\vispWrapper-build\ViSPUnity.vcxproj]
D:\VisualStudioPJ\visp-ws\visp_unity\vispWrapper\ViSPUnity.cpp(158,5): error C2065: 'klt_settings': undeclared identifi
er [D:\VisualStudioPJ\visp-ws\visp_unity\vispWrapper-build\ViSPUnity.vcxproj]
D:\VisualStudioPJ\visp-ws\visp_unity\vispWrapper\ViSPUnity.cpp(159,5): error C2065: 'klt_settings': undeclared identifi
er [D:\VisualStudioPJ\visp-ws\visp_unity\vispWrapper-build\ViSPUnity.vcxproj]
D:\VisualStudioPJ\visp-ws\visp_unity\vispWrapper\ViSPUnity.cpp(160,5): error C2065: 'klt_settings': undeclared identifi
er [D:\VisualStudioPJ\visp-ws\visp_unity\vispWrapper-build\ViSPUnity.vcxproj]
D:\VisualStudioPJ\visp-ws\visp_unity\vispWrapper\ViSPUnity.cpp(161,5): error C2065: 'klt_settings': undeclared identifi
er [D:\VisualStudioPJ\visp-ws\visp_unity\vispWrapper-build\ViSPUnity.vcxproj]
D:\VisualStudioPJ\visp-ws\visp_unity\vispWrapper\ViSPUnity.cpp(162,5): error C2065: 'klt_settings': undeclared identifi
er [D:\VisualStudioPJ\visp-ws\visp_unity\vispWrapper-build\ViSPUnity.vcxproj]
D:\VisualStudioPJ\visp-ws\visp_unity\vispWrapper\ViSPUnity.cpp(163,27): error C2039: 'setKltOpencv': is not a member of
 'vpMbGenericTracker' [D:\VisualStudioPJ\visp-ws\visp_unity\vispWrapper-build\ViSPUnity.vcxproj]
D:\VisualStudioPJ\visp-ws\visp-build-vc16\install\include\visp3/mbt/vpMbGenericTracker.h(80): message : see declaration
 of 'vpMbGenericTracker' [D:\VisualStudioPJ\visp-ws\visp_unity\vispWrapper-build\ViSPUnity.vcxproj]
D:\VisualStudioPJ\visp-ws\visp_unity\vispWrapper\ViSPUnity.cpp(163,28): error C2065: 'klt_settings': undeclared identif
ier [D:\VisualStudioPJ\visp-ws\visp_unity\vispWrapper-build\ViSPUnity.vcxproj]
D:\VisualStudioPJ\visp-ws\visp_unity\vispWrapper\ViSPUnity.cpp(164,31): error C2039: 'setKltMaskBorder': is not a membe
r of 'vpMbGenericTracker' [D:\VisualStudioPJ\visp-ws\visp_unity\vispWrapper-build\ViSPUnity.vcxproj]
D:\VisualStudioPJ\visp-ws\visp-build-vc16\install\include\visp3/mbt/vpMbGenericTracker.h(80): message : see declaration
 of 'vpMbGenericTracker' [D:\VisualStudioPJ\visp-ws\visp_unity\vispWrapper-build\ViSPUnity.vcxproj]
D:\VisualStudioPJ\visp-ws\visp_unity\vispWrapper\ViSPUnity.cpp(169,1): warning C4273: 'Visp_MbGenericTracker_Init': inc
onsistent dll linkage [D:\VisualStudioPJ\visp-ws\visp_unity\vispWrapper-build\ViSPUnity.vcxproj]
D:\VisualStudioPJ\visp-ws\visp_unity\vispWrapper\ViSPUnity.h(134,6): message : see previous definition of 'Visp_MbGener
icTracker_Init' [D:\VisualStudioPJ\visp-ws\visp_unity\vispWrapper-build\ViSPUnity.vcxproj]
D:\VisualStudioPJ\visp-ws\visp_unity\vispWrapper\ViSPUnity.cpp(187,1): warning C4273: 'Visp_MbGenericTracker_Process':
inconsistent dll linkage [D:\VisualStudioPJ\visp-ws\visp_unity\vispWrapper-build\ViSPUnity.vcxproj]
D:\VisualStudioPJ\visp-ws\visp_unity\vispWrapper\ViSPUnity.h(175,6): message : see previous definition of 'Visp_MbGener
icTracker_Process' [D:\VisualStudioPJ\visp-ws\visp_unity\vispWrapper-build\ViSPUnity.vcxproj]
D:\VisualStudioPJ\visp-ws\visp_unity\vispWrapper\ViSPUnity.cpp(295,1): warning C4273: 'Visp_MbGenericTracker_CreateCaoF
ile': inconsistent dll linkage [D:\VisualStudioPJ\visp-ws\visp_unity\vispWrapper-build\ViSPUnity.vcxproj]
D:\VisualStudioPJ\visp-ws\visp_unity\vispWrapper\ViSPUnity.h(93,6): message : see previous definition of 'Visp_MbGeneri
cTracker_CreateCaoFile' [D:\VisualStudioPJ\visp-ws\visp_unity\vispWrapper-build\ViSPUnity.vcxproj]
D:\VisualStudioPJ\visp-ws\visp_unity\vispWrapper\ViSPUnity.cpp(329,1): warning C4273: 'Visp_CameraParameters_Init': inc
onsistent dll linkage [D:\VisualStudioPJ\visp-ws\visp_unity\vispWrapper-build\ViSPUnity.vcxproj]
D:\VisualStudioPJ\visp-ws\visp_unity\vispWrapper\ViSPUnity.h(188,6): message : see previous definition of 'Visp_CameraP
arameters_Init' [D:\VisualStudioPJ\visp-ws\visp_unity\vispWrapper-build\ViSPUnity.vcxproj]
D:\VisualStudioPJ\visp-ws\visp_unity\vispWrapper\ViSPUnity.cpp(334,1): warning C4273: 'Visp_DetectorAprilTag_Init': inc
onsistent dll linkage [D:\VisualStudioPJ\visp-ws\visp_unity\vispWrapper-build\ViSPUnity.vcxproj]
D:\VisualStudioPJ\visp-ws\visp_unity\vispWrapper\ViSPUnity.h(199,6): message : see previous definition of 'Visp_Detecto
rAprilTag_Init' [D:\VisualStudioPJ\visp-ws\visp_unity\vispWrapper-build\ViSPUnity.vcxproj]
D:\VisualStudioPJ\visp-ws\visp_unity\vispWrapper\ViSPUnity.cpp(345,1): warning C4273: 'Visp_DetectorAprilTag_Process':
inconsistent dll linkage [D:\VisualStudioPJ\visp-ws\visp_unity\vispWrapper-build\ViSPUnity.vcxproj]
D:\VisualStudioPJ\visp-ws\visp_unity\vispWrapper\ViSPUnity.h(233,6): message : see previous definition of 'Visp_Detecto
rAprilTag_Process' [D:\VisualStudioPJ\visp-ws\visp_unity\vispWrapper-build\ViSPUnity.vcxproj]

**Comment by fspindle** [comment]
I did a commit to fix the warnings
For the build errors it sounds that ViSP build was not linked to OpenCV.
Check if `%VISP_WS%\visp-build-vc16\ViSP-third-party.txt` has a line
```
C:\visp-ws\visp_unity\vispWrapper-build-vc15\Release
```

**Comment by LungTakumi** [comment]
Yes, I found the reason previously, it is because OpenCV was not installed. Anyway, thx for support!
