### ISSUE TITLE
‘KLT_TRACKER’ is not a member of ‘vpMbGenericTracker’

### ISSUE THREAD

**Issue by bkaraceylan** [lagadic/visp_unity#23]
Hello,

I'm trying to build vispWrapper following exactly the official tutorial for installation on Ubuntu 20.04.02. However I am getting this error: "error: ‘KLT_TRACKER’ is not a member of ‘vpMbGenericTracker’". I've installed all recommended 3rd party libraries.

**Comment by fspindle** [comment]
It means that ViSP was not build with OpenCV support.

**Comment by bkaraceylan** [comment]
Thanks, my opencv directory environmental variable was not set for some reason.
