### ISSUE TITLE
what is the meaning of cog and height in detection AprilTag ?

### ISSUE THREAD

**Issue by meroua16** [lagadic/visp_unity#24]
hi  
i can't understand the meaning of tag_cog[x0 x1] and tag_height [h0 h1 h2 h3 h4 h5]
on the other hand it's OK for the homogeneous matrix tag_cMo

do you have any idea ?

**Comment by fspindle** [comment]
From the [doc(https://github.com/lagadic/visp_unity/blob/master/vispWrapper/ViSPUnity.h)

 * \param tag_cog : 2-dim array that contains tag center of gravity coordinates (u, v) along horizontal
 * and vertical axis respectively.
 * \param tag_length : 6-dim array that contains the length in pixel of the 4 tag sides and the length of the tag diagonal.
