### ISSUE TITLE
Dll not found after reinstallation of VISP - visp_io351.dll not found

### ISSUE THREAD

**Issue by VarnL0** [lagadic/visp_unity#28]
I have an error right after the installation of Visp and dataset, when I try to run the first example with displayGDI.exe I end up with this error : 

visp_io351.dll not found. Reinstalling the program can help to solve this problem.

I reinstalled the program and the dataset but I end up with the exact same error at the same moment even though the installation worked perfectly.
<img width="301" alt="image" src="https://user-images.githubusercontent.com/98879616/219345557-55ee24ff-5988-4f40-8392-a35bcd171000.png">

**Comment by fspindle** [comment]
You forgot to add the location of ViSP DLL in your path env var as explained in the [tutorial](https://visp-doc.inria.fr/doxygen/visp-daily/tutorial-install-win10-msvc17.html#install_win10_msvc17_env_var)
