### ISSUE TITLE
Get the webcam image from unity, and pass the bitmap to a function of the plugin to convert it in a vpImage

### ISSUE THREAD

**Issue by MarcPouliquenInria** [lagadic/visp_unity#6]
The goal is to capture webcam frames in unity, and pass them to the plugin (by using the pixels array). Then convert the array in a vpImage.
- To use the webcam in Unity, and get the bitmap array, here is an helpful examle :  [unity webcam texture](https://docs.unity3d.com/ScriptReference/WebCamTexture.GetPixels32.html)
- To display the webcam image in unity, this [link](https://docs.unity3d.com/ScriptReference/WebCamTexture.Play.html) will help

**Comment by aryamihirs** [comment]
I have started working on it.

**Comment by MarcPouliquenInria** [comment]
Ok, thanks ! On my side I just comitted to add a basic doxygen config (to write some tutorials), and added OS selection to correctly export functions of vispWraper (btw I tested to compile your dot_product  code on fedora, and to run it in unity : It works well). 
So if you can update your fork with the new commit before your next pull request it will be nice (to avoid some conflicts on merging)
