### ISSUE TITLE
1 blob tracking from unity

### ISSUE THREAD

**Issue by MarcPouliquenInria** [lagadic/visp_unity#7]
The goal of this task is to use the visp blob tracker in Unity.
The [tutorial for blob tracking](http://visp-doc.inria.fr/doxygen/visp-daily/tutorial-tracking-blob.html) is a good start to understand how to use the tracker.

**Comment by aryamihirs** [comment]
While reading the documentation of flush() function I found that it must be used in order to see the overlay on the current frame.

How to pass the updated frame, without using flush(). (since we can't in unity). Or will the frame be updated in the same vpImage variable (image)?

**Comment by MarcPouliquenInria** [comment]
Flush is a method of vpDisplay (to display an image in a window). But for the project, all the rendering is done in Unity, so we don't need tu use vpDisplay.
The plugin code won't write on the image, it will just return the position of the dot tracked (in pixels coodinates for the beginning). You can use the following method to achieve this : 
`void vpDot2::track (const vpImage< unsigned char > &  	I,vpImagePoint & ) `
`vpImagePoint` contains the coordinates.
Then, back in unity side, you can use these coodrinates : 
- by logging them at the beginning (it will be enough to complete this issue)
- in order to place place a gameObject in the unity scene after. But to achieve this properly, knowing camera and scene parameters will be necessary. So a calibration part will be needed to link the real scene (the webcam and the tracked dot), to the virtual scene in unity (unity  camera parameters and size and position of the GameObject inserted). This point will be part of next issue

**Comment by aryamihirs** [comment]
This can be closed now I think?
